# Generated by Django 5.1.7 on 2025-03-24 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_hours', models.IntegerField(default=70)),
                ('cycle_days', models.IntegerField(default=8)),
                ('fuel_interval_miles', models.IntegerField(default=1000)),
                ('pickup_dropoff_time_hours', models.FloatField(default=1.0)),
                ('route_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driving_hours', models.FloatField()),
                ('rest_hours', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='trip.trip')),
            ],
        ),
    ]
