# Generated by Django 5.1.7 on 2025-03-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.JSONField(),
        ),
    ]
