# Generated by Django 5.1.7 on 2025-03-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_trip_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eldlog',
            name='rests',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eldlog',
            name='stops',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
