# Generated by Django 5.1.7 on 2025-03-26 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0003_eldlog_rests_eldlog_stops"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="cycle_hours",
            new_name="current_cycle",
        ),
    ]
