# Generated by Django 5.1.7 on 2025-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0005_eldlog_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eldlog",
            name="rests",
        ),
        migrations.RemoveField(
            model_name="eldlog",
            name="stops",
        ),
        migrations.AddField(
            model_name="trip",
            name="rests",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="stops",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eldlog",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
