# Generated by Django 5.1.7 on 2025-03-26 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0006_remove_eldlog_rests_remove_eldlog_stops_trip_rests_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="route_data",
            new_name="metadata",
        ),
    ]
