# Generated by Django 5.1.7 on 2025-03-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0007_rename_route_data_trip_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eldlog",
            name="metadata",
        ),
        migrations.AddField(
            model_name="eldlog",
            name="day_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="eldlog",
            name="distance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="eldlog",
            name="driving_hours",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="eldlog",
            name="rest_hours",
            field=models.FloatField(null=True),
        ),
    ]
